### ISSUE TITLE
Clicking fast twice at middle mouse button(roll) cause to show a glitched bar

### ISSUE THREAD

**Issue by qarmin** [P1X-in/Tanks-of-Freedom-3-D#10]
https://user-images.githubusercontent.com/41945903/132041013-3040a108-c4ff-46c0-9f19-e4f34007131a.mp4

**Comment by czlowiekimadlo** [comment]
I'm not sure if I understand the issue, I have to try reproducing it myself. Holding middle mouse button is supposed to fill up the bar and end the turn, quickly clicking it will show and hide the bar, which should start from the beginning every time.

**Comment by qarmin** [comment]
When I click very quickly at the middle mouse button, then looks that sometimes value changes to lower
e.g. 
normal behavior - value always increase
```
0 1 2 3 4 5 6 7 8 9 filled
```
current behavior - sometimes for a moment value decrease(it is better visible in 0.25x or 0.5x speed)
```
0 1 2 3 4   2   5 6   3   7 8   4   9 filled
```

(look at time bar), not even 0.5 second later, value become lower and a little later it become higher
![Screenshot from 2021-09-04 07-55-46](https://user-images.githubusercontent.com/41945903/132084377-64a5aeb7-51f4-4c8b-830f-6d910a0709a5.png)

![Screenshot from 2021-09-04 07-55-54](https://user-images.githubusercontent.com/41945903/132084380-16f7b7f0-0fb2-4790-8bb3-6fac7901f15f.png)

![Screenshot from 2021-09-04 08-01-53](https://user-images.githubusercontent.com/41945903/132084536-034c9f79-f4d8-4786-9e7f-02ef206d8add.png)

**Comment by czlowiekimadlo** [comment]
Well, yes, it is supposed to reset to 0 every time you release the MMB and click it again. It is more of a bug that sometimes it does not.

**Comment by czlowiekimadlo** [comment]
I have tried reproducing this issue today and was not able to. I think I remember fixing this in the past, so probably can be closed.
