### ISSUE TITLE
defence shield shown even if unit does not defend

### ISSUE THREAD

**Issue by JPT77** [P1X-in/Tanks-of-Freedom-3-D#12]
In TOF-0.7.1 Android the shield indicating defense is often shown even if the unit does not defend. I saw it once after continuing a game. but it happens during normal gameplay too, I think.
(I kill the game if I made a mistake in my turn, then reopen)

thanks

ps. sorry, wrong project. where is TOF I?

**Comment by czlowiekimadlo** [comment]
Hey JPT77! Thank you for your report. I'm afraid ToF 1 is not being developed anymore, I just released 0.7.1 because I had some fixes hanging around for years, and it needed an SSL cert refresh. This repository is for ToF 2, so this issue does not apply.
