### ISSUE TITLE
If you try to put tile in editor with coordinates too big(55, 61), game is crashing

### ISSUE THREAD

**Issue by GaidamakUA** [P1X-in/Tanks-of-Freedom-3-D#7]
No time to fix it myself ATM, hopefully some time later.

**Comment by czlowiekimadlo** [comment]
Interesting, how did you manage to do that over ui? I thought that both mouse and gamepad were bound so that they could not go outside the usable area.

Anyway, should be easy to fix as soon as I stop slacking off in Starbase.

**Comment by GaidamakUA** [comment]
Yeah, it should be limited. I cant reproduce it anymore.

**Comment by czlowiekimadlo** [comment]
Placed additional protection just in case 8f9da13
